import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const DATA_FILE = join(HERE, 'catalog', 'events.json')

/**
 * Read-only access to the dataset exported from the frontend.
 *
 * `data/events.json` is generated by `npm run export:events` at the repo
 * root, which runs the real date engine. Nothing in the backend recomputes
 * a recurrence rule -- if code here ever starts doing date maths beyond
 * comparing two ISO strings, something has gone wrong.
 */
export function loadCatalog(path = DATA_FILE) {
  const raw = JSON.parse(readFileSync(path, 'utf8'))
  const events = new Map(raw.events.map((e) => [e.id, e]))

  // The latest year any published, checked date covers. Once the calendar
  // passes this, every regulated event silently falls back to its estimated
  // recurrence rule -- which is correct behaviour but worth being told about,
  // because it means new official dates are waiting to be entered.
  const confirmedThrough = raw.occurrences.reduce(
    (max, o) => (o.confirmed ? Math.max(max, Number(o.start.slice(0, 4))) : max),
    0,
  )
  return {
    generatedAt: raw.generatedAt,
    years: raw.years,
    categories: raw.categories ?? [],
    events,
    occurrences: raw.occurrences,
    confirmedThrough,
  }
}
