import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const DATA_FILE = join(HERE, 'catalog', 'events.json')

/**
 * Read-only access to the dataset exported from the frontend.
 *
 * `data/events.json` is generated by `npm run export:events` at the repo
 * root, which runs the real date engine. Nothing in the backend recomputes
 * a recurrence rule -- if code here ever starts doing date maths beyond
 * comparing two ISO strings, something has gone wrong.
 */
export function loadCatalog(path = DATA_FILE) {
  const raw = JSON.parse(readFileSync(path, 'utf8'))
  const events = new Map(raw.events.map((e) => [e.id, e]))
  return {
    generatedAt: raw.generatedAt,
    years: raw.years,
    events,
    occurrences: raw.occurrences,
  }
}
